define(function() {
    return {
        "properties": [{
            "name": "username",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "Title",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isUsernameVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isProfileVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isLoginVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["btnLoginClick"]
    }
});